version: '3.1'

services:
  postgres:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"


